# Generated by Django 3.2 on 2022-01-04 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('code_coverage', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'verbose_name': 'UNIT тест',
                'verbose_name_plural': 'UNIT тесты',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='E2ETest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('manual', models.PositiveIntegerField(default=0)),
                ('automated', models.PositiveIntegerField(default=0)),
                ('coverage', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'verbose_name': 'E2E тест',
                'verbose_name_plural': 'E2E тесты',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='APITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('full_coverage', models.FloatField(default=0)),
                ('partial_coverage', models.FloatField(default=0)),
                ('empty_coverage', models.FloatField(default=100)),
                ('actual_cnt', models.PositiveIntegerField(default=0)),
                ('full_cnt', models.PositiveIntegerField(default=0)),
                ('partial_cnt', models.PositiveIntegerField(default=0)),
                ('empty_cnt', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'verbose_name': 'API тест',
                'verbose_name_plural': 'API тесты',
                'ordering': ['project'],
            },
        ),
    ]
