# Generated by Django 3.1.4 on 2021-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSwaggerCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('full_coverage', models.FloatField()),
                ('partial_coverage', models.FloatField()),
                ('empty_coverage', models.FloatField()),
                ('full_cnt', models.FloatField()),
                ('partial_cnt', models.FloatField()),
                ('actual_cnt', models.FloatField()),
            ],
        ),
    ]
