# Generated by Django 3.1.4 on 2021-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonswaggercoverage',
            name='empty_cnt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
