# Generated by Django 3.2 on 2022-01-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APITest',
            new_name='APICoverage',
        ),
        migrations.RenameModel(
            old_name='E2ETest',
            new_name='E2ECoverage',
        ),
        migrations.RenameModel(
            old_name='UnitTest',
            new_name='UnitCoverage',
        ),
        migrations.AlterModelOptions(
            name='apicoverage',
            options={'ordering': ['project'], 'verbose_name': 'API coverage', 'verbose_name_plural': 'API coverage'},
        ),
        migrations.AlterModelOptions(
            name='e2ecoverage',
            options={'ordering': ['project'], 'verbose_name': 'E2E coverage', 'verbose_name_plural': 'E2E coverage'},
        ),
        migrations.AlterModelOptions(
            name='unitcoverage',
            options={'ordering': ['project'], 'verbose_name': 'UNIT coverage', 'verbose_name_plural': 'UNIT coverage'},
        ),
    ]
