# Generated by Django 3.1.4 on 2021-12-01 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commonswaggercoverage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonswaggercoverage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
