# Generated by Django 3.1.4 on 2021-11-30 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211130_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonswaggercoverage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
